# Add/remove 'critical' label if issue contains the words 'urgent' or 'critical'
critical:
    - '(critical|urgent)'

knowledge panels:
    - '(kp|knowledge panels)'

layout:
    - '(layout)'
    
database:
    - '(database)'
    
mlkit:
    - '(mlkit)'
